$(document).ready(function() {
    // Sample list of suggestions (can be fetched from an API)
    var suggestions = [
        "Apple", "Banana", "Cherry", "Date", "Grape", "Lemon", "Mango", "Orange", "Peach", "Pear",
        "Pineapple", "Strawberry", "Watermelon", "Apricot", "Avocado", "Blueberry", "Coconut", "Fig", "Kiwi", "Lychee",
        "Papaya", "Pomegranate", "Raspberry", "Tomato", "Cantaloupe", "Plum", "Cranberry", "Blackberry", "Guava", "Passionfruit",
        "Dragonfruit", "Mangosteen", "Pineberry", "Starfruit", "Persimmon", "Kumquat", "Durian", "Jackfruit", "Lime", "Clementine",
        "Tangerine", "Nectarine", "Grapefruit", "Melon", "Mulberry", "Bilberry", "Rhubarb", "Cactus", "Elderberry", "Feijoa",
        "Huckleberry", "Juniperberry", "Boysenberry", "Loganberry", "Soursop", "Ackee", "Carambola", "Longan", "Sapodilla", "Tamarillo",
        "Miracle fruit", "Persimmon", "Quince", "Ugli fruit", "Yangmei", "Açaí", "Babaco", "Breadfruit", "Chayote", "Pepino",
        "Squash", "Custard apple", "Barbadine", "Bignay", "Black sapote", "Canistel", "Carissa", "Chebulic myrobalan", "Cloudberry", "Cupuaçu",
        "Damson", "Elephant apple", "Gac", "Gambooge", "Horned melon", "Jabuticaba", "Jambul", "Kiwano", "Kundong", "Langsat",
        "Mamey sapote", "Marang", "Monkey fruit", "Noni", "Pitaya", "Pulasan", "Rambutan", "Salak", "Satsuma", "Sea grape",
        "Tamarind", "Wampee", "Yuzu", "Zalzalak", "Saskatoon berry", "Yardlong", "Snake fruit", "Umbu",

        // Additional words
        "Apricots", "Blackcurrant", "Star apple", "Peach palm", "Peaches and cream", "Lemonade fruit", "Blue raspberry", "Strawberry guava",
        "Watermelon sugar", "Cucumber melon", "Passion fruit juice", "Dragon fruit punch", "Mango salsa", "Orange marmalade", "Limeade",
        "Nectarine tree", "Grape soda", "Black cherry cola", "Kiwi strawberry", "Lychee martini", "Papaya smoothie", "Pomegranate seed",
        "Raspberry ripple", "Tomato soup", "Cantaloupe sorbet", "Plum pudding", "Cranberry sauce", "Blackberry jam", "Guava jelly",
        "Passionfruit cheesecake", "Dragonfruit sorbet", "Mangosteen juice", "Pineberry tart", "Starfruit salad", "Persimmon cake",
        "Kumquat pie", "Durian ice cream", "Jackfruit curry", "Clementine syrup", "Tangerine twist", "Nectarine cobbler", "Grapefruit mimosa",
        "Melon ball", "Mulberry wine", "Bilberry pie", "Rhubarb crumble", "Elderberry wine", "Feijoa chutney", "Huckleberry pie",
        "Juniperberry gin", "Boysenberry cobbler", "Loganberry jam", "Soursop juice", "Ackee and saltfish", "Carambola juice",
        "Longan fruit salad", "Sapodilla pudding", "Tamarillo salsa", "Miracle fruit tablets", "Persimmon tea", "Quince jelly",
        "Ugli fruit salad", "Yangmei fruit wine", "Açaí bowl", "Babaco fruit salad", "Breadfruit chips", "Chayote squash soup",
        "Pepino fruit salad", "Squash casserole", "Custard apple pie", "Barbadine smoothie", "Bignay wine", "Black sapote pudding",
        "Canistel custard", "Carissa jam", "Chebulic myrobalan pickle", "Cloudberry jam", "Cupuaçu butter", "Damson plum jam",
        "Elephant apple chutney", "Gac fruit juice", "Gambooge extract", "Horned melon sorbet", "Jabuticaba jelly", "Jambul fruit punch",
        "Kiwano salad", "Kundong jam", "Langsat fruit wine", "Mamey sapote milkshake", "Marang ice cream", "Monkey fruit smoothie",
        "Noni fruit leather", "Pitaya dragon fruit bowl", "Pulasan fruit salad", "Rambutan fruit syrup", "Salak snake fruit chips",
        "Satsuma mandarin orange", "Sea grape salad", "Tamarind paste", "Wampee fruit jelly", "Yuzu fruit tea", "Zalzalak fruit jam",
        "Saskatoon berry pie", "Yardlong bean stir-fry", "Snake fruit wine", "Umbu fruit salad",

        // Additional words -2
        "Plantain", "Tangelo", "Ugni", "Velvet apple", "Wood apple", "Yam", "Zapote", "African cherry", "Bael fruit", "Cocoa bean",
        "Date palm", "Eggfruit", "Finger lime", "Granadilla", "Honeydew melon", "Imbe", "Java apple", "Kepel fruit", "Langsat",
        "Mangaba", "Nance fruit", "Olive", "Pomelo", "Quince", "Rose apple", "Salmonberry", "Tamarillo", "Ugni", "Vanilla bean",
        "Wax apple", "Yellow passion fruit", "Zucchini", "Acerola cherry", "Balsam apple", "Cherimoya", "Duku fruit", "Elephant apple",
        "Finger lime", "Garcinia indica", "Honeyberry", "Ice cream bean", "Jujube", "Kiwifruit", "Lingonberry", "Miracle fruit", "Nance",
        "Olive fruit", "Peach palm", "Quince fruit", "Rambutan", "Star apple", "Tamarind fruit", "Umbu", "Velvet tamarind", "White currant",
        "Xylocarp", "Yellow passionfruit", "Zinfandel grape",

        // Additional words - 3
        "Apple", "Almond", "Bread", "Butter", "Cake", "Cheese", "Chicken", "Chocolate", "Coffee", "Cookie",
        "Egg", "Fish", "Honey", "Ice cream", "Juice", "Meat", "Milk", "Nuts", "Olive oil", "Pasta",
        "Rice", "Salt", "Sausage", "Soup", "Tea", "Tofu", "Vinegar", "Wine", "Yogurt", "Burger",
        "Pizza", "Sandwich", "Salad", "Fruit salad", "Pancake", "Waffle", "French fries", "Onion rings", "Popcorn", "Nachos",
        "Taco", "Burrito", "Sushi", "Tempura", "Ramen", "Pad thai", "Pho", "Biryani", "Samosa", "Gyoza",
        "Spring roll", "Dim sum", "Kebab", "Shawarma", "Falafel", "Lasagna", "Spaghetti", "Carbonara", "Ravioli", "Cannelloni",
        "Gnocchi", "Fettuccine", "Macaroni", "Tiramisu", "Cheesecake", "Brownie", "Cupcake", "Muffin", "Croissant", "Bagel",
        "Donut", "Cinnamon roll", "Pretzel", "Chips", "Doritos", "Cheetos", "Peanut butter", "Nutella", "Jam", "Marmalade",
        "Syrup", "Hummus", "Guacamole", "Tzatziki", "Pesto", "Salsa", "Barbecue sauce", "Mustard", "Mayonnaise", "Ketchup",
        "Soy sauce", "Teriyaki sauce", "Worcestershire sauce", "Tabasco", "Sriracha", "Hoisin sauce", "Wasabi", "Horseradish", "Vinaigrette",
        "Caesar dressing", "Ranch dressing", "Thousand island dressing", "Blue cheese dressing", "Balsamic glaze", "Hollandaise sauce", "Bechamel sauce", "Marinara sauce", "Alfredo sauce", "Pesto sauce",
        "Tomato sauce", "Chili sauce", "Hot sauce", "Sour cream", "Cream cheese", "Ricotta cheese", "Feta cheese", "Parmesan cheese", "Mozzarella cheese",
        "Cheddar cheese", "Gouda cheese", "Brie cheese", "Camembert cheese", "Goat cheese", "Burrata cheese", "Halloumi cheese", "Paneer cheese", "Blue cheese",
        "Swiss cheese", "Provolone cheese", "Emmental cheese", "Gruyere cheese", "Monterey Jack cheese", "Colby cheese", "Pepper jack cheese", "Havarti cheese", "Fontina cheese",
        "Limburger cheese", "Boursin cheese", "Gorgonzola cheese", "Roquefort cheese", "Manchego cheese", "Edam cheese", "Muenster cheese", "Danish blue cheese", "Stilton cheese", "Queso fresco cheese",
        "Queso blanco cheese", "Ricotta salata cheese", "Cottage cheese", "Panela cheese", "Queso Oaxaca cheese", "Taleggio cheese", "Jarlsberg cheese", "Cotija cheese", "Grana Padano cheese", "Pecorino Romano cheese",
        "Ghee", "Clarified butter", "Butter oil", "Cocoa powder", "Chocolate chips", "Chocolate syrup", "Coconut milk", "Condensed milk", "Evaporated milk", "Almond milk",
        "Soy milk", "Oat milk", "Rice milk", "Cashew milk", "Hazelnut milk", "Macadamia milk", "Walnut milk", "Pistachio milk", "Hemp milk", "Flax milk",
        "Quinoa milk", "Banana milk", "Cinnamon milk", "Vanilla milk", "Mango milk", "Papaya milk", "Pineapple milk", "Strawberry milk", "Blueberry milk", "Raspberry milk",

        // Additional words -4 
        "Potato", "Carrot", "Onion", "Garlic", "Lettuce", "Tomato", "Cucumber", "Bell pepper", "Broccoli", "Spinach",
        "Cabbage", "Celery", "Mushroom", "Zucchini", "Eggplant", "Pumpkin", "Sweet potato", "Corn", "Peas", "Green beans",
        "Asparagus", "Radish", "Beetroot", "Turnip", "Cauliflower", "Brussels sprouts", "Artichoke", "Kale", "Swiss chard", "Endive",
        "Fennel", "Leek", "Parsnip", "Rutabaga", "Scallion", "Watercress", "Arugula", "Bok choy", "Chard", "Collard greens",
        "Mustard greens", "Rapini", "Turnip greens", "Acorn squash", "Butternut squash", "Hubbard squash", "Spaghetti squash", "Kabocha squash", "Delicata squash",
        "Pattypan squash", "Zephyr squash", "Yellow squash", "Zucchini squash", "Ginger", "Turmeric", "Cinnamon", "Clove", "Nutmeg",
        "Cardamom", "Allspice", "Vanilla", "Bay leaf", "Basil", "Oregano", "Thyme", "Rosemary", "Sage", "Dill",
        "Mint", "Parsley", "Coriander", "Cilantro", "Chives", "Tarragon", "Marjoram", "Lemon zest", "Orange zest", "Lime zest",
        "Grapefruit zest", "Clementine zest", "Tangerine zest", "Chocolate chips", "Chopped nuts", "Sprinkles", "Crushed candy", "Shredded coconut", "Raisins",
        "Dried cranberries", "Dried apricots", "Dried figs", "Dried dates", "Dried prunes", "Dried mango", "Dried papaya", "Dried pineapple", "Dried banana", "Dried apple",
        "Granola", "Oats", "Chia seeds", "Flaxseeds", "Sunflower seeds", "Pumpkin seeds", "Sesame seeds", "Poppy seeds", "Hemp seeds", "Quinoa",
        "Brown rice", "White rice", "Basmati rice", "Jasmine rice", "Wild rice", "Barley", "Bulgur", "Farro", "Millet", "Couscous",
        "Polenta", "Cornmeal", "Wheat flour", "All-purpose flour", "Whole wheat flour", "Bread flour", "Cake flour", "Pastry flour", "Rye flour", "Corn flour",
        "Semolina flour", "Almond flour", "Coconut flour", "Gluten-free flour", "Olive oil", "Coconut oil", "Canola oil", "Vegetable oil", "Sunflower oil",
        "Sesame oil", "Peanut oil", "Grapeseed oil", "Avocado oil", "Flaxseed oil", "Walnut oil", "Soybean oil", "Butter", "Ghee", "Margarine",
        "Shortening", "Heavy cream", "Half-and-half", "Whipped cream", "Sour cream", "Cream cheese", "Cottage cheese", "Ricotta cheese", "Mascarpone cheese",
        "Creme fraiche", "Yogurt", "Greek yogurt", "Almond milk", "Soy milk", "Coconut milk", "Oat milk", "Rice milk", "Cashew milk",
        "Hazelnut milk", "Macadamia milk", "Walnut milk", "Pistachio milk", "Hemp milk", "Flax milk", "Quinoa milk", "Banana milk", "Chocolate milk",
        "Strawberry milk", "Blueberry milk", "Vanilla milk", "Coconut water", "Tonic water", "Club soda", "Ginger ale", "Cola", "Root beer",
        "Lemon-lime soda", "Orange soda", "Grape soda", "Cream soda", "Apple cider", "Cranberry juice", "Grape juice", "Orange juice", "Pineapple juice",
        "Tomato juice", "Vegetable juice", "Apple juice", "Pear juice", "Lemonade", "Limeade", "Fruit punch", "Iced tea", "Hot tea", "Green tea",
        "Black tea", "White tea", "Herbal tea", "Chamomile tea", "Peppermint tea", "Ginger tea", "Cinnamon tea", "Hibiscus tea", "Rooibos tea",
        "Earl Grey tea", "English breakfast tea", "Oolong tea", "Matcha tea", "Coffee", "Espresso", "Latte", "Cappuccino", "Americano",
        "Mocha", "Macchiato", "Irish coffee", "Caramel macchiato", "Affogato", "Frappuccino", "Iced coffee", "Coffee with milk", "Coffee with sugar", "Coffee with cream",

        // Additional words - 5
        "Potato", "Carrot", "Onion", "Garlic", "Lettuce", "Cucumber", "Broccoli", "Spinach", "Cabbage", "Celery",
        "Mushroom", "Pumpkin", "Corn", "Peas", "Green beans", "Asparagus", "Radish", "Beetroot", "Turnip", "Cauliflower",
        "Brussels sprouts", "Artichoke", "Kale", "Ginger", "Turmeric", "Cinnamon", "Nutmeg", "Cardamom", "Bay leaf", "Oregano",
        "Rosemary", "Sage", "Dill", "Mint", "Parsley", "Coriander", "Chives", "Tarragon", "Basil", "Thyme",
        "Peppercorn", "Cloves", "Fennel seeds", "Mustard seeds", "Poppy seeds", "Cumin seeds", "Sesame seeds", "Flaxseeds", "Sunflower seeds", "Pumpkin seeds",
        "Chia seeds", "Hemp seeds", "Quinoa", "Brown rice", "Basmati rice", "Jasmine rice", "Wild rice", "Barley", "Bulgur",
        "Couscous", "Millet", "Oats", "Bread", "Pasta", "Spaghetti", "Macaroni", "Lasagna", "Ravioli", "Gnocchi",
        "Fettuccine", "Farfalle", "Orzo", "Cannelloni", "Tortellini", "Tagliatelle", "Vermicelli", "Rice noodles", "Soba noodles", "Udon noodles",
        "Ramen noodles", "Pad Thai noodles", "Buckwheat noodles", "Sushi rice", "Vinegar", "Balsamic vinegar", "Apple cider vinegar", "White vinegar", "Red wine vinegar",
        "Rice vinegar", "Coconut vinegar", "Distilled vinegar", "Malt vinegar", "Honey", "Maple syrup", "Agave nectar", "Molasses", "Corn syrup", "Golden syrup",
        "Treacle", "Peanut butter", "Almond butter", "Cashew butter", "Hazelnut butter", "Sunflower seed butter", "Tahini", "Coconut butter", "Soy sauce", "Tamari",
        "Fish sauce", "Oyster sauce", "Worcestershire sauce", "Hoisin sauce", "Sriracha", "Tabasco", "Wasabi", "Mirin", "Rice wine", "Sherry",
        "White wine", "Red wine", "Marsala", "Sake", "Beer", "Ale", "Stout", "Lager", "Pilsner", "Porter",
        "Cider", "Gin", "Vodka", "Rum", "Tequila", "Whiskey", "Brandy", "Cognac", "Aquavit", "Absinthe",
        "Sambuca", "Amaretto", "Baileys", "Kahlua", "Triple sec", "Cointreau", "Grand Marnier", "Frangelico", "Chambord", "Curaçao",
        "Grenadine", "Simple syrup", "Margarita mix", "Bloody Mary mix", "Piña colada mix", "Mint syrup", "Lavender syrup", "Ginger syrup", "Cardamom syrup",

        // Additional words -6 
        "LOL", "OMG", "ROFL", "ICYMI", "BRB", "TTYL", "AFK", "FTW", "IDK", "TBH",
        "YOLO", "FOMO", "GOAT", "SUS", "TIL", "Woke", "Yeet", "Bae", "Slay", "Flex",
        "Vibe", "Glow up", "Simp", "Thirsty", "Fam", "Lit", "Savage", "Woke", "Ghosting", "Swipe",
        "DM", "Squad", "Mood", "Snack", "Clout", "Shade", "Tea", "Stan", "FOMO", "JOMO",
        "Hangry", "Bougie", "Basic", "Ship", "OTP", "Smh", "TL;DR", "WTF", "JK", "IDC",
        "NSFW", "FWB", "YOLO", "Salty", "Glow up", "Throw shade", "Tea", "Thirst trap", "Lit", "Shade",
        "Woke", "Cancel culture", "On fleek", "Low key", "High key", "AF", "Thicc", "Vibing", "Wig", "Flexin",

        // Additional words - 7
        "Goal", "Touchdown", "Basket", "Strike", "Point", "Goalkeeper", "Goalie", "Pitch", "Court", "Field",
        "Track", "Ring", "Arena", "Stadium", "Pitcher", "Catcher", "Batter", "Striker", "Forward", "Defender",
        "Midfielder", "Attacker", "Goalie", "Goalkeeper", "Wicket", "Batsman", "Bowler", "All-rounder", "Sweeper", "Libero",
        "Serve", "Ace", "Deuce", "Game", "Set", "Match", "Tournament", "Cup", "League", "Championship",
        "Finals", "Semifinals", "Quarterfinals", "Round", "Knockout", "Group stage", "Qualifiers", "Playoffs", "Relegation",
        "Promotion", "Medal", "Gold", "Silver", "Bronze", "Podium", "Record", "World record", "Personal best", "Time",
        "Speed", "Distance", "Height", "Weight", "Strength", "Power", "Endurance", "Agility", "Flexibility",
        "Coordination", "Technique", "Skill", "Strategy", "Tactics", "Teamwork", "Communication", "Leadership", "Sportsmanship",
        "Fair play", "Respect", "Dedication", "Commitment", "Passion", "Drive", "Motivation", "Inspiration", "Role model",
        "Athlete", "Player", "Competitor", "Opponent", "Rival", "Coach", "Manager", "Referee", "Umpire", "Official",
        "Fan", "Supporter", "Cheerleader", "Mascot", "Champion", "Winner", "Runner-up", "Finalist", "Contender", "Underdog",
        "Legend", "Icon", "Hero", "Superstar", "Professional", "Amateur", "Training", "Practice", "Warm-up", "Cooldown",
        "Stretching", "Exercise", "Drill", "Workout", "Session", "Regimen", "Routine", "Preparation", "Recovery",
        "Rest", "Injury", "Rehabilitation", "Physiotherapy", "Treatment", "Fitness", "Conditioning", "Nutrition", "Hydration",
        "Diet", "Calories", "Protein", "Carbohydrates", "Fats", "Vitamins", "Minerals", "Supplements", "Performance",
        "Peak", "Zone", "Flow", "Adrenaline", "Excitement", "Nerves", "Pressure", "Anxiety", "Focus", "Concentration",

        //  AW -8 Poliiocal words 
        "Government", "Politics", "Democracy", "Republic", "Monarchy", "Dictatorship", "Oligarchy", "Autocracy", "Theocracy", "Anarchy",
    "Constitution", "Citizenship", "Election", "Voting", "Poll", "Referendum", "Campaign", "Candidate", "Party", "Coalition",
    "Opposition", "Legislation", "Law", "Bill", "Amendment", "Policy", "Jurisdiction", "Administration", "Executive", "Legislature",
    "Judiciary", "President", "Prime Minister", "Chancellor", "Monarch", "Dictator", "Emperor", "Sultan", "King", "Queen",
    "Congress", "Parliament", "Senate", "House of Representatives", "Cabinet", "Minister", "Ambassador", "Diplomat", "Foreign affairs", "International relations",
    "Domestic affairs", "National security", "Defense", "Military", "Armed forces", "Security council", "Peacekeeping", "Alliance", "Treaty",
    "Negotiation", "Diplomacy", "Summit", "Agreement", "Protocol", "Declaration", "Resolution", "Sanction", "Embargo", "Trade",
    "Tariff", "Customs", "Border", "Immigration", "Emigration", "Asylum", "Refugee", "Migration", "Citizenship",
    "Nationality", "Passport", "Visa", "Identity", "Registration", "Census", "Demography", "Population", "Constituency",
    "District", "Province", "State", "Territory", "Region", "City", "Town", "Village", "Electoral district",
    "Constituency", "Precinct", "Ward", "Polling station", "Polling booth", "Ballot", "Ballot paper", "Ballot box", "Voting machine",
    "Electoral commission", "Election commission", "Supervisor of elections", "Polling officer", "Returning officer", "Electoral fraud", "Vote rigging", "Gerrymandering",
    "Political party", "Major party", "Minor party", "Independent", "Liberal", "Conservative", "Socialist", "Communist", "Fascist",
    "Green", "Populist", "Nationalist", "Centrist", "Left-wing", "Right-wing", "Radical", "Reformist", "Moderate",
    "Extremist", "Reactionary", "Progressive", "Libertarian", "Authoritarian", "Conservatism", "Liberalism", "Socialism", "Communism",
    "Fascism", "Anarchism", "Capitalism", "Globalization", "Free trade", "Protectionism", "Welfare state", "Social democracy", "Mixed economy",
    "Public sector", "Private sector", "Nationalization", "Privatization", "Government spending", "Taxation", "Revenue", "Budget", "Deficit",
    "Debt", "Inflation", "Interest rate", "Exchange rate", "Monetary policy", "Fiscal policy", "Economic growth", "Gross domestic product", "Unemployment",
    "Poverty", "Income inequality", "Wealth inequality", "Social welfare", "Healthcare", "Education", "Housing", "Transportation", "Infrastructure",
    "Environment", "Climate change", "Sustainability", "Renewable energy", "Carbon footprint", "Emissions", "Pollution", "Conservation", "Biodiversity",
    "Natural resources", "Water management", "Land management", "Forestry", "Agriculture", "Fisheries", "Mining", "Energy policy", "Nuclear energy",
    "Wind energy", "Solar energy", "Hydropower", "Geothermal energy", "Bioenergy", "Fossil fuels", "Oil", "Natural gas", "Coal",
    "Petroleum", "Geopolitics", "Geography", "Territorial dispute", "Colonialism", "Imperialism", "Decolonization", "Global governance", "World order",
    "International law", "Human rights", "Civil rights", "Political rights", "Freedom of speech", "Freedom of press", "Freedom of assembly", "Freedom of religion",
    "Freedom of movement", "Right to privacy", "Right to protest", "Right to vote", "Rule of law", "Separation of powers", "Checks and balances", "Civil society",
    "Civil disobedience", "Political activism", "Protest", "Demonstration", "Rally", "March", "Sit-in", "Boycott", "Strike", "Revolution",
    "Coup", "Uprising", "Resistance", "Solidarity", "Rebellion", "Insurgency", "Terrorism", "Counterterrorism", "National security", "Homeland security",
    "State security", "Intelligence", "Surveillance", "Espionage", "Cryptography", "Cybersecurity", "Information warfare", "Propaganda", "Disinformation", "Fake news",
    "Media manipulation", "Political censorship", "Political correctness", "Public opinion", "Polling", "Opinion poll", "Survey", "Opinion survey", "Approval rating",
    "Election forecasting", "Exit poll", "Opinion leader", "Influencer", "Spin doctor", "Political consultant", "Campaign manager", "Press secretary", "Political analyst",
    "Political commentator", "Pundit", "Journalist", "Reporter", "Correspondent", "Columnist", "Editor", "Publisher", "Newspaper", "Magazine",
    "Television", "Radio", "Internet", "Social media", "Blog", "Podcast", "Forum", "Website", "Online platform", "Digital media",
    "Information technology", "Artificial intelligence", "Big data", "Machine learning", "Data analytics", "Algorithm", "Computer", "Software", "Hardware",
    "Programming", "Internet of things", "Cloud computing", "Blockchain", "Cryptocurrency", "Bitcoin", "Ethereum", "Decentralization", "Smart contract", "Token",
    "Digital currency", "Virtual reality", "Augmented reality", "Cyberspace", "Digital divide", "Digital literacy", "Cyberbullying", "Cyberattack", "Cyberwarfare",
    "Online privacy", "Data protection", "Encryption", "Anonymous", "Hacker", "Cracker", "Phishing", "Malware", "Virus", "Trojan horse",
    "Worm", "Spyware", "Ransomware", "Botnet", "Denial of service", "Cybersecurity", "Cybercrime", "Dark web", "Deep web", "Surface web",

    // AW -9 Tech words 
    "Technology", "Internet", "Software", "Hardware", "Programming", "Code", "Algorithm", "Data", "Database", "Server",
    "Client", "Cloud", "Virtualization", "Operating system", "Browser", "Application", "App", "Website", "Webpage", "Web server",
    "Web hosting", "Domain", "URL", "HTTP", "HTTPS", "HTML", "CSS", "JavaScript", "PHP", "Python",
    "Java", "C++", "C#", "Ruby", "Swift", "Objective-C", "SQL", "NoSQL", "Database management system", "Relational database",
    "Non-relational database", "Big data", "Data analytics", "Data science", "Machine learning", "Artificial intelligence", "Deep learning", "Neural network",
    "Computer vision", "Natural language processing", "Speech recognition", "Chatbot", "Blockchain", "Cryptocurrency", "Bitcoin", "Ethereum", "Smart contract",
    "Decentralized finance", "DeFi", "NFT", "Non-fungible token", "Cryptocurrency wallet", "Digital wallet", "Decentralized application", "DApp", "Metaverse", "Virtual reality",
    "Augmented reality", "Mixed reality", "Extended reality", "Gaming", "Video game", "Mobile game", "Console game", "PC game", "Online game",
    "MMORPG", "MOBA", "First-person shooter", "Battle royale", "Role-playing game", "Strategy game", "Simulation game", "Puzzle game", "Arcade game",
    "Platformer", "Indie game", "Game development", "Game design", "Game engine", "Unity", "Unreal Engine", "Godot", "CryEngine",
    "Lumberyard", "Figma", "Sketch", "Adobe XD", "InVision", "Prototyping", "Wireframing", "UI design", "UX design",
    "User interface", "User experience", "Responsive design", "Mobile design", "Desktop design", "Web design", "Graphic design", "Logo design", "Illustration",
    "Animation", "Motion graphics", "Video editing", "3D modeling", "CAD", "Computer-aided design", "Rendering", "Visual effects", "VFX",
    "Digital art", "Photo editing", "Image manipulation", "Raster graphics", "Vector graphics", "Typography", "Font", "Typeface", "Open source",
    "GitHub", "GitLab", "Bitbucket", "Version control", "Repository", "Commit", "Branch", "Merge", "Fork",
    "Pull request", "Issue", "Bug", "Feature", "Enhancement", "Documentation", "Readme", "License", "MIT license",
    "GNU license", "Apache license", "BSD license", "Creative Commons license", "GPL", "Copyleft", "Public domain", "Stack Overflow", "Developer",
    "Programmer", "Coder", "Software engineer", "Web developer", "Frontend developer", "Backend developer", "Full-stack developer", "Mobile developer", "iOS developer",
    "Android developer", "Game developer", "Unity developer", "Unreal Engine developer", "UI designer", "UX designer", "Graphic designer", "Product designer", "Interaction designer",
    "Design system", "Component library", "Frontend framework", "Backend framework", "JavaScript framework", "Node.js", "React", "Vue.js", "Angular",
    "Express", "Django", "Flask", "Ruby on Rails", "ASP.NET", "Spring", "Laravel", "Symfony", "CodeIgniter",
    "WordPress", "Drupal", "Joomla", "Magento", "Shopify", "Squarespace", "Wix", "Webflow", "Firebase", "AWS",
    "Amazon Web Services", "Google Cloud Platform", "Microsoft Azure", "Heroku", "DigitalOcean", "Linode", "VPS", "VPN",
    "Domain registrar", "Hosting provider", "Content delivery network", "CDN", "Serverless", "Microservices", "Containerization", "Docker", "Kubernetes",
    "Continuous integration", "CI/CD", "DevOps", "Infrastructure as code", "IaC", "Automation", "Scripting", "Shell scripting", "Bash",
    "Python scripting", "PowerShell", "Batch scripting", "Ansible", "Chef", "Puppet", "SaltStack", "Monitoring", "Logging",
    "Alerting", "Incident management", "Security", "Cybersecurity", "Network security", "Information security", "Ethical hacking", "Penetration testing", "Firewall",
    "Encryption", "SSL", "TLS", "Authentication", "Authorization", "Identity management", "Access control", "Multi-factor authentication", "Biometric authentication", "Password management",
    "Zero trust", "Endpoint security", "Malware", "Virus", "Trojan", "Ransomware", "Spyware", "Phishing", "Social engineering", "Cyber attack",
    "Data breach", "Vulnerability", "Exploit", "Patch", "Security audit", "Compliance", "GDPR", "CCPA", "HIPAA",
    "PCI DSS", "ISO 27001", "NIST", "Privacy policy", "Terms of service", "Digital rights", "Net neutrality", "Cyber law", "Internet governance",
    "Digital divide", "Access to information", "Freedom of expression", "Censorship", "Surveillance", "Privacy", "Data protection", "Online safety",
    "Cyberbullying", "Trolling", "Fake news", "Disinformation", "Misinformation", "Fact-checking", "Content moderation", "Algorithmic bias", "Filter bubble",
    "Echo chamber", "Online community", "Social media", "Social network", "Social platform", "Facebook", "Twitter", "Instagram", "LinkedIn",
    "Snapchat", "TikTok", "Reddit", "YouTube", "WhatsApp", "Messenger", "WeChat", "Discord", "Slack",
    "Signal", "Telegram", "Clubhouse", "Viber", "Line", "KakaoTalk", "Sina Weibo", "QQ", "Baidu Tieba",
    "Minds", "Gab", "Parler", "MeWe", "VKontakte", "Odnoklassniki", "Renren", "YY", "Toutiao",
    "Weibo", "WeChat", "Douyin", "Kuaishou", "Bilibili", "Zhihu", "Quora", "Yelp", "Foursquare",
    "TripAdvisor", "Booking.com", "Expedia", "Skyscanner", "Airbnb", "Uber", "Lyft", "Grab", "Gojek",
    "Didi Chuxing", "Ola", "Food delivery", "E-commerce", "Online shopping", "Amazon", "eBay", "Alibaba", "AliExpress",
    "Taobao", "Tmall", "JD.com", "Walmart", "Target", "Best Buy", "Apple Store", "Google Store", "Microsoft Store",
    "App Store", "Google Play", "iOS", "Android", "Smartphone", "iPhone", "Samsung", "Huawei", "Xiaomi",
    "OnePlus", "Google Pixel", "LG", "Sony", "HTC", "Motorola", "Nokia", "BlackBerry", "Tablet",
    "iPad", "Samsung Galaxy Tab", "Microsoft Surface", "Amazon Fire Tablet", "Huawei MediaPad", "Lenovo Tab", "Chromebook", "Laptop", "MacBook",
    "Windows laptop", "Mac laptop", "Chromebook", "Desktop computer", "PC", "Mac", "iMac", "Mac Pro", "Mac mini",
    "Windows PC", "Gaming PC", "All-in-one PC", "Workstation", "Graphics card", "GPU", "CPU", "Processor", "Motherboard",
    "RAM", "Memory", "Storage", "Hard drive", "SSD", "Flash drive", "Cloud storage", "File sharing", "FTP",
    "Dropbox", "Google Drive", "OneDrive", "Box", "WeTransfer", "FileZilla", "WinSCP", "Cyberduck", "PuTTY",
    "SSH", "Telnet", "Remote desktop", "VNC", "TeamViewer", "AnyDesk", "Screen sharing", "Webinar", "Web conference",
    "Video call", "Voice call", "Messaging", "Instant messaging", "Chat", "Email", "SMS", "MMS", "VoIP",
    "Skype", "Zoom", "Microsoft Teams", "Google Meet", "Cisco Webex", "Slack", "Discord", "WhatsApp", "Signal",
    "Telegram", "Viber", "Line", "KakaoTalk", "WeChat", "Facebook Messenger", "Instagram Direct", "Snapchat", "TikTok",
    "Reddit", "Twitter", "LinkedIn", "Dating app", "Tinder", "Bumble", "Grindr", "OkCupid", "Match.com",
    "eHarmony", "Hinge", "Coffee Meets Bagel", "Plenty of Fish", "Facebook Dating", "Zoosk", "Her", "Scruff", "Happn",
    "BLK", "Chispa", "Jdate", "JSwipe", "Christian Mingle", "Muslima", "Shaadi", "EliteSingles", "SilverSingles",
    "SeniorMatch", "OurTime", "DateMyAge", "FirstMet", "Meetup", "Eventbrite", "Facebook Events", "Ticketmaster", "StubHub",
    "Fandango", "Cinema", "Movie theater", "TV", "Television", "Streaming", "Streaming service", "Video on demand", "SVOD",
    "Netflix", "Amazon Prime Video", "Hulu", "Disney+", "Apple TV+", "HBO Max", "YouTube Premium", "Twitch", "Twitch.tv",
    "Livestreaming", "Live video", "Vlog", "YouTuber", "Content creator", "Podcast", "Podcasting", "Audio streaming", "Music streaming",
    "Spotify", "Apple Music", "Amazon Music", "Tidal", "SoundCloud", "Deezer", "Pandora", "iHeartRadio", "SiriusXM",
    "Radio", "Internet radio", "Satellite radio", "Smart speaker", "Amazon Echo", "Echo Dot", "Echo Show", "Google Home", "Nest Audio",
    "Apple HomePod", "Sonos", "Smart home", "Home automation", "IoT", "Internet of Things", "Smart device", "Smart appliance", "Smart thermostat",
    "Smart lighting", "Smart lock", "Smart camera", "Smart doorbell", "Security camera", "Video doorbell", "Baby monitor", "Pet camera", "Robot vacuum",
    "Robotic cleaner", "Roomba", "Neato", "Ecovacs", "Samsung Powerbot", "iRobot", "Litter-Robot", "PetSafe", "Furbo", "Nest",
    "Ring", "Arlo", "Wyze", "Blink", "August", "Netatmo", "Wink", "SmartThings", "Z-Wave", "Zigbee",
    "IFTTT", "Smart grid", "Renewable energy", "Solar panel", "Solar power", "Wind turbine", "Wind power", "Hydropower", "Geothermal energy",
    "Biomass", "Biofuel", "Electric vehicle", "EV", "Tesla", "Nissan Leaf", "Chevrolet Bolt", "BMW i3", "Hyundai Kona Electric",
    "Ford Mustang Mach-E", "Volkswagen ID.4", "Audi e-tron", "Rivian R1T", "Lucid Air", "Electric car", "Electric scooter", "E-scooter",
    "Segway", "Bird", "Lime", "Spin", "Razor", "Xiaomi", "Ninebot", "Gogoro", "Electric bike", "E-bike",
    "Peloton", "Exercise bike", "Stationary bike", "Indoor cycling", "Fitness", "Fitness tracker", "Activity tracker", "Fitbit", "Garmin",
    "Apple Watch", "Smartwatch", "Wearable device", "Wearable technology", "Health", "Healthcare", "Telemedicine", "Telehealth", "Online doctor",
    "Virtual doctor", "Doctor on demand", "Health insurance", "Medical records", "Electronic health record", "EHR", "Patient portal", "Pharmacy",
    "Online pharmacy", "Prescription", "Medication", "Medicine", "Pharmaceutical", "Health app", "Wellness", "Mental health", "Therapy",
    "Counseling", "Psychiatry", "Psychology", "Mindfulness", "Meditation", "Yoga", "Fitness app", "Diet", "Nutrition",
    "Meal planning", "Healthy eating", "Food delivery", "Meal kit", "Grocery delivery", "Online grocery", "Food service", "Restaurant",
    "Takeout", "Delivery", "Uber Eats", "DoorDash", "Grubhub", "Postmates", "Instacart", "Amazon Fresh", "Whole Foods",
    "Health food", "Organic food", "Vegetarian", "Vegan", "Plant-based", "Gluten-free", "Dairy-free", "Keto", "Paleo",
    "Low-carb", "Low-fat", "Weight loss", "Calorie counting", "Intermittent fasting", "Fitness tracker", "Step counter", "Sleep tracking", "Heart rate monitor",
    "Blood pressure monitor", "Blood glucose monitor", "Pregnancy tracker", "Baby tracker", "Family tracker", "Pet tracker", "Pet care", "Pet health",
    "Dog walking", "Dog sitting", "Pet grooming", "Pet training", "Dog training", "Cat care", "Cat grooming", "Cat sitting",
    "Cat training", "Pet food", "Pet supplies", "Pet toys", "Pet accessories", "Pet insurance", "Pet adoption", "Animal shelter", "Animal rescue",
    "Animal welfare", "Animal rights", "Pet-friendly", "Dog-friendly", "Cat-friendly", "Pet hotel", "Dog park", "Cat cafe", "Pet store",
    "Pet website", "Pet community", "Pet forum", "Pet blog", "Pet influencer", "Pet social media", "Dog breed", "Cat breed",
    "Dog breed selector", "Cat breed selector", "Dog breed encyclopedia", "Cat breed encyclopedia", "Dog name", "Cat name", "Pet name",
    "Dog training tips", "Cat training tips", "Pet grooming tips", "Dog health", "Cat health", "Pet health insurance", "Pet behavior", "Dog behavior",
    "Cat behavior", "Pet therapy", "Dog therapy", "Cat therapy", "Animal therapy", "Pet loss", "Pet memorial", "Pet funeral",
    "Pet cemetery", "Pet grief", "Pet bereavement", "Pet memorial jewelry", "Pet portrait", "Custom pet portrait", "Pet photography", "Pet drawing",
    "Pet painting", "Pet sculpture", "Pet tattoo", "Pet story", "Pet biography", "Pet history", "Pet blog", "Pet memoir",
    "Pet fiction", "Pet poetry", "Pet essay", "Pet nonfiction", "Pet book", "Pet novel", "Pet movie", "Pet documentary",
    "Pet TV show", "Pet website", "Pet social media", "Pet influencer", "Pet celebrity", "Pet fame", "Pet viral",
    "Pet trend", "Pet culture", "Pet community", "Pet fan", "Pet lover", "Pet owner", "Pet parent", "Pet caregiver",
    "Pet sitter", "Pet walker", "Pet transporter", "Pet nanny", "Pet daycare", "Pet boarding", "Pet hotel", "Pet spa",
    "Pet store", "Pet shop", "Pet boutique", "Pet bakery", "Pet cafe", "Pet restaurant", "Pet bar", "Pet pub",
    "Pet hotel", "Pet resort", "Pet retreat", "Pet sanctuary", "Pet park", "Pet beach", "Pet garden", "Pet trail",
    "Pet hike", "Pet walk", "Pet jog", "Pet run", "Pet race", "Pet contest", "Pet show", "Pet parade",
    "Pet festival", "Pet fair", "Pet expo", "Pet convention", "Pet conference", "Pet seminar", "Pet workshop", "Pet class",
    "Pet lesson", "Pet training", "Pet education", "Pet therapy", "Pet healing", "Pet wellness", "Pet health", "Pet care",
    "Pet nutrition", "Pet diet", "Pet exercise", "Pet play", "Pet toy", "Pet game", "Pet puzzle", "Pet treat",
    "Pet snack", "Pet meal", "Pet food", "Pet drink", "Pet water", "Pet bed", "Pet blanket", "Pet pillow",
    "Pet mattress", "Pet cushion", "Pet carrier", "Pet stroller", "Pet sling", "Pet tote", "Pet backpack", "Pet purse",
    "Pet coat", "Pet sweater", "Pet hoodie", "Pet jacket", "Pet shirt", "Pet dress", "Pet skirt", "Pet pants",
    "Pet hat", "Pet cap", "Pet visor", "Pet bandana", "Pet bow tie", "Pet tie", "Pet scarf", "Pet necklace",
    "Pet collar", "Pet harness", "Pet leash", "Pet tag", "Pet charm", "Pet accessory", "Pet jewelry", "Pet watch",
    "Pet clock", "Pet ornament", "Pet decor", "Pet furniture", "Pet house", "Pet bed", "Pet cave", "Pet tent",
    "Pet teepee", "Pet igloo", "Pet hut", "Pet palace", "Pet castle", "Pet mansion", "Pet villa", "Pet castle",
    "Pet palace", "Pet castle", "Pet mansion", "Pet villa", "Pet castle", "Pet palace", "Pet castle", "Pet mansion",
    "Pet villa", "Pet castle", "Pet palace", "Pet castle", "Pet mansion", "Pet villa", "Pet castle", "Pet palace",
    "Pet castle", "Pet mansion", "Pet villa", "Pet castle", "Pet palace", "Pet castle", "Pet mansion", "Pet villa",
    "Pet castle", "Pet palace", "Pet castle", "Pet mansion", "Pet villa", "Pet castle", "Pet palace", "Pet castle",
    "Pet mansion", "Pet villa", "Pet castle", "Pet palace", "Pet castle", "Pet mansion", "Pet villa", "Pet castle",

    // AW-10 Geographical and all worlds main cities and conutries
     // Geographical Features
     "Mount Everest", "Mariana Trench", "Amazon Rainforest", "Sahara Desert", "Great Barrier Reef", 
     "Grand Canyon", "Victoria Falls", "Paricutin Volcano", "Mount Kilimanjaro", "Yellowstone National Park", 
     "Gobi Desert", "Dead Sea", "Niagara Falls", "Mount Fuji", "Angel Falls", 
     "Great Wall of China", "K2", "Victoria Peak", "K2", "Mount Elbrus", 
     "Yosemite National Park", "Antarctica", "Arctic Ocean", "Pacific Ocean", "Atlantic Ocean", 
     "Indian Ocean", "Caribbean Sea", "Mediterranean Sea", "Black Sea", "Red Sea", 
     "Baltic Sea", "North Sea", "Gulf of Mexico", "Himalayas", "Andes Mountains", 
     "Rocky Mountains", "Alps", "Appalachian Mountains", "Ural Mountains", "Caucasus Mountains", 
     "Huangshan", "Mount Etna", "Uluru", "Pamukkale", "Mount Rainier", 
     "Mount Cook", "Denali", "Mount Rushmore", "Matterhorn", "Mount McKinley", 
     "Lake Baikal", "Crater Lake", "Lake Titicaca", "Caspian Sea", "Lake Victoria", 
     "Lake Tanganyika", "Lake Superior", "Lake Michigan", "Lake Huron", "Lake Erie", 
     "Lake Ontario", "Great Lakes", "Nile River", "Amazon River", "Yangtze River", 
     "Mississippi River", "Yellow River", "Yukon River", "Ganges River", "Mekong River", 
     "Danube River", "Rhine River", "Volga River", "Tigris River", "Euphrates River", 
     "Indus River", "Colorado River", "Congo River", "Murray River", "Zambezi River", 
     "River Thames", "Seine River", "Loire River", "Amazon Basin", "Mississippi Basin", 
     "Ganges Basin", "Murray-Darling Basin", "Orinoco Basin", "Rio Grande", "Danube Delta", 
     "Nile Delta", "Ganges Delta", "Amazon Delta", "Mekong Delta", "Mississippi Delta", 
     "Everglades", "Okavango Delta", "Great Victoria Desert", "Atacama Desert", "Thar Desert", 
     "Sahel", "Kalahari Desert", "Savannah", "Prairie", "Taiga", 
     "Tundra", "Polar Ice Caps", "Fjord", "Glacier", "Iceberg", 
     "Cape of Good Hope", "Cape Horn", "Cape Canaveral", "Cape Cod", "Cape York Peninsula", 
     "Isthmus of Panama", "Strait of Gibraltar", "Strait of Hormuz", "Strait of Malacca", "Strait of Magellan", 
     "Bering Strait", "Hudson Bay", "Bay of Bengal", "Bay of Fundy", "Hudson Bay", 
     "Chesapeake Bay", "San Francisco Bay", "Hudson Bay", "Hudson Bay", "Hudson Bay", 
     "Puget Sound", "Galapagos Islands", "Azores", "Hawaiian Islands", "Svalbard", 
     "Falkland Islands", "Easter Island", "Santorini", "Socotra", "Bora Bora", 
     "Tahiti", "Maldives", "Seychelles", "Bali", "Phuket", 
     "Crete", "Ibiza", "Hvar", "Cabo San Lucas", "Cancun", 
     "Bora Bora", "Maui", "Maui", "Bora Bora", "Hvar", 
     "Bora Bora", "Bora Bora", "Hvar", "Maui",

    //  AW-11 
    "Tokyo", "New York City", "London", "Paris", "Los Angeles",
    "Moscow", "Beijing", "Shanghai", "Rio de Janeiro", "Cairo",
    "Mexico City", "Mumbai", "Delhi", "Kolkata", "Bangalore",
    "Chennai", "Hyderabad", "Ahmedabad", "Pune", "Surat",
    "Jaipur", "Kanpur", "Nagpur", "Lucknow", "Indore",
    "Patna", "Bhopal", "Ludhiana", "Agra", "Vadodara",
    "Nashik", "Faridabad", "Meerut", "Rajkot", "Kalyan-Dombivali",
    "Vasai-Virar", "Varanasi", "Srinagar", "Aurangabad", "Dhanbad",
    "Amritsar", "Navi Mumbai", "Allahabad", "Howrah", "Ranchi",
    "Gwalior", "Jabalpur", "Coimbatore", "Vijayawada", "Jodhpur",
    "Madurai", "Raipur", "Kota", "Guwahati", "Chandigarh",
    "Solapur", "Hubballi-Dharwad", "Bareilly", "Moradabad", "Mysore",
    "Gurgaon", "Aligarh", "Jalandhar", "Tiruchirappalli", "Bhubaneswar",
    "Salem", "Warangal", "Guntur", "Bhiwandi", "Saharanpur",
    "Gorakhpur", "Bikaner", "Amravati", "Noida", "Jamshedpur",
    "Bhilai", "Cuttack", "Firozabad", "Kochi", "Nellore",
    "Bhavnagar", "Dehradun", "Durgapur", "Asansol", "Rourkela",
    "Nanded", "Kolhapur", "Ajmer", "Akola", "Gulbarga",
    "Jamnagar", "Ujjain", "Loni", "Siliguri", "Jhansi",
    "Ulhasnagar", "Nellore", "Jammu", "Sangli-Miraj & Kupwad", "Belgaum",
    "Mangalore", "Ambattur", "Tirunelveli", "Malegaon", "Gaya",
    "Jalgaon", "Udaipur", "Maheshtala", "Davanagere", "Kozhikode",
    "Akola", "Kurnool", "Rajpur Sonarpur", "Bokaro", "South Dumdum",
    "Bellary", "Patiala", "Gopalpur", "Agartala", "Bhagalpur",
    "Muzaffarnagar", "Bhatpara", "Panihati", "Latur", "Dhule",
    "Rohtak", "Sagar", "Korba", "Bhilwara", "Brahmapur",
    "Muzaffarpur", "Ahmednagar", "Mathura", "Kollam", "Avadi",
    "Kadapa", "Kamarhati", "Sambalpur", "Bilaspur", "Shahjahanpur",
    "Satara", "Bijapur", "Rampur", "Shivamogga", "Chandrapur",
    "Junagadh", "Thrissur", "Alwar", "Bardhaman", "Kulti",
    "Nizamabad", "Parbhani", "Tumkur", "Khammam", "Ozhukarai",
    "Bihar Sharif", "Panipat", "Darbhanga", "Bally", "Aizawl",
    "Dewas", "Ichalkaranji", "Tirupati", "Gurgaon", "Sagar",
    "Bharatpur", "Mahesana", "Barasat", "Rayong", "Si Racha",
    "Surat Thani", "Phitsanulok", "Chon Buri", "Chiang Rai", "Nakhon Si Thammarat",
    "Hat Yai", "Udon Thani", "Pak Kret", "Khon Kaen", "Ubon Ratchathani",
    "Nakhon Ratchasima", "Nakhon Sawan", "Chiang Mai", "Bangkok", "Yokohama",
    "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kobe",
    "Kyoto", "Saitama", "Hiroshima", "Sendai", "Kitakyushu",
    "Chiba", "Sakai", "Niigata", "Hamamatsu", "Okayama",
    "Kawasaki", "Sagamihara", "Funabashi", "Hachioji", "Kumamoto",
    "Kanazawa", "Shizuoka", "Hirakata", "Utsunomiya", "Gifu",
    "Toyama", "Nara", "Matsuyama", "Nishinomiya", "Kurashiki",
    "Oita", "Miyazaki", "Akita", "Fukushima", "Kofu",
    "Maebashi", "Sasebo", "Amagasaki", "Otsu", "Wakayama",
    "Koriyama", "Tokorozawa", "Kashiwa", "Toyohashi", "Nagano",
    "Iwaki", "Asahikawa", "Nagasaki", "Takatsuki", "Suita",
    "Hakodate", "Hachinohe", "Kure", "Chigasaki", "Atsugi",
    "Numazu", "Shimonoseki", "Fuchu", "Neyagawa", "Nagaoka",
    "Miyakonojo", "Hiratsuka", "Yamato", "Himeji", "Kakogawa",
    "Kawaguchi", "Soka", "Matsumoto", "Kanoya", "Odawara",
    "Tokushima", "Shimizu", "Nishitokyo", "Takasaki", "Ibaraki",
    "Fukui", "Naha", "Toyokawa", "Nagareyama", "Seto",
    "Beppu", "Tsu", "Kashihara", "Matsue", "Takarazuka",
    "Ise", "Shimada", "Kumagaya", "Ogaki", "Kariya",
    "Isesaki", "Aomori", "Ube", "Joetsu", "Tondabayashi",
    "Katsuta", "Muroran", "Saiki", "Yao", "Narita",
    "Uji", "Kurume", "Ishinomaki", "Omiya", "Otaru",
    "Takasago", "Kure", "Kani", "Hikone", "Minamirinkan",
    "Morioka", "Hirado", "Koganei", "Urayasu", "Inazawa",
    "Higashimurayama", "Wakkanai", "Hino", "Tochigi", "Yamaguchi",
    "Yokkaichi", "Higashiosaka", "Tendo", "Fukaya", "Ikeda",
    "Tokuyama", "Niihama", "Matsudo", "Uwajima", "Kazo",
    "Iga", "Odawara", "Takayama", "Fukagawa", "Iwakuni",
    "Nirasaki", "Kure", "Nishiwaki", "Yamagata", "Yao",
    "Niigata", "Naha", "Takaoka", "Akashi", "Oyama",
    "Seto", "Yachimata", "Tatsuno", "Ichihara", "Hirosaki",
    "Tsuyama", "Iwade", "Tateyama", "Toda", "Hakusan",
    "Itoigawa", "Nishinoomote", "Ishikawa", "Higashikurume", "Nasushiobara",
    "Murakami", "Sakata", "Kunitachi", "Kyotango", "Taketa",
    "Chikusei", "Tsukuba", "Kurashiki", "Kariya", "Matsusaka",
    "Kasama", "Shirakawa", "Tomioka", "Ito", "Kashima",
    "Fujisawa", "Iida", "Koshigaya", "Okinawa", "Shiroishi",
    "Kamakura", "Yokote", "Numazu", "Kokubunji", "Fujimi",
    "Shinshiro", "Chikushino", "Hita", "Ogori", "Itami",
    "Yamamoto", "Tsushima", "Kikuchi", "Onomichi", "Kamaishi",
    "Nanao", "Kakegawa", "Hanno", "Kawanishi", "Kochi",
    "Tsuruga", "Nishimuro", "Ishigaki", "Nagahama", "Taketoyo",
    "Takahashi", "Kisarazu", "Tanabe", "Shibetsu", "Rumoi",
    "Kamisu", "Toyonaka", "Kamogawa", "Komatsu", "Makurazaki",
    "Tatsuno", "Nakama", "Yamaguchi", "Ogawa", "Imabari",
    "Sanda", "Ogose", "Ageo", "Nanto", "Yuki",
    "Yaita", "Higashikawa", "Otaru", "Ogano", "Kiryu",
    "Kumagaya", "Ogano", "Kiryu", "Isesaki", "Kumagaya",
    "Miyakonojo", "Nagayo", "Otsu", "Akune", "Kushiro",
    "Fukui", "Yamada", "Takahata", "Kure", "Higashihiroshima",
    "Omuta", "Tomakomai", "Fukuchiyama", "Yurihonjo", "Fujisawa",
    "Fujieda", "Naze", "Tateyama", "Imizu", "Asahi",
    "Furukawa", "Osaki", "Tsushima", "Takahama", "Tokuyama",
    "Kimitsu", "Shiojiri", "Kunitachi", "Anjo", "Ito",
    "Towada", "Muroto", "Hikone", "Saiki", "Yokote",
    "Kakegawa", "Tawaramoto", "Nakamura", "Yokkaichi", "Miki",
    "Kaminokawa", "Kumagaya", "Murakami", "Yokote", "Gosen",
    "Shirone", "Nagaoka", "Kaminoyama", "Kure", "Hofu",
    "Saiki", "Kunitachi", "Asahi", "Ito", "Shiojiri",
    "Takahama", "Kimitsu", "Nagayo", "Imizu", "Osaki",
    "Furukawa", "Omuta", "Tomakomai", "Muroto", "Fujieda",
    "Naze", "Muroto", "Shiojiri", "Omuta", "Kimitsu",
    "Kure", "Nakamura", "Kakegawa", "Kunitachi", "Yokkaichi",
    "Kure", "Murakami", "Furukawa", "Yokkaichi", "Imizu",
    "Hikone", "Hofu", "Shirone", "Miki", "Shiojiri",
    "Nagayo", "Hofu", "Shiojiri", "Kimitsu", "Kakegawa",
    "Miki", "Furukawa", "Imizu", "Hikone", "Fujieda",
    "Naze", "Yokkaichi", "Kure", "Tomakomai", "Omuta",
    "Kure", "Tomakomai", "Yokkaichi", "Kure", "Tomakomai"
];

    // Function to update suggestions list based on user input
    function updateSuggestions(inputValue) {
        var filteredSuggestions = suggestions.filter(function(suggestion) {
            return suggestion.toLowerCase().startsWith(inputValue.toLowerCase());
        });
        
        displaySuggestions(filteredSuggestions);
    }

    // Function to display suggestions in the list
    function displaySuggestions(suggestionsArray) {
        var suggestionsList = $('#suggestionsList');
        suggestionsList.empty();

        suggestionsArray.forEach(function(suggestion) {
            var listItem = $('<li>').text(suggestion);
            suggestionsList.append(listItem);
        });

        // Add click event listener to select a suggestion
        suggestionsList.on('click', 'li', function() {
            $('#searchInput').val($(this).text());
            suggestionsList.empty();
        });
    }

    // Event listener for input changes
    $('#searchInput').on('input', function() {
        var inputValue = $(this).val();
        if (inputValue.length >= 1) {
            updateSuggestions(inputValue);
        } else {
            $('#suggestionsList').empty();
        }
    });

    // Event listener to handle ESC key press to clear suggestions
    $(document).on('keydown', function(event) {
        if (event.key === "Escape") {
            $('#suggestionsList').empty();
        }
    });

    // Event listener to handle clicking outside the input field to clear suggestions
    $(document).on('click', function(event) {
        if (!$(event.target).closest('#searchInput').length) {
            $('#suggestionsList').empty();
        }
    });
});
